/**
 * Frontend AI Service — STUB INTERFACE CONTRACT
 * Single plug-in point for future RAG / LLM stack.
 */

export interface ToothAnalysisRequest {
  patientId: string;
  toothId: string;
}

export interface ToothAnalysisResponse {
  status: "stub" | "live";
  message: string;
  reportId?: string;
  contextSnapshot: Record<string, unknown>;
  result: {
    mockDiagnosis?: string;
    confidence?: number;
    recommendedProcedure?: string;
    urgency?: string;
  } | null;
}

export interface ChatMessageStub {
  id: string;
  sender: "user" | "assistant";
  text: string;
  isStub?: boolean;
  createdAt: string;
}

export interface ReportGenerationRequest {
  patientId: string;
  templateType: "tooth-analysis" | "patient-summary" | "treatment-plan";
  title?: string;
}

export interface ReportPreviewResponse {
  isMock: boolean;
  title: string;
  markdownContent: string;
}

export const aiServiceStub = {
  analyzeTooth: async (
    req: ToothAnalysisRequest,
  ): Promise<ToothAnalysisResponse> => {
    // Standard stub response matching backend /api/ai/analyze-tooth endpoint
    return {
      status: "stub",
      message:
        "AI engine not connected — interface ready. Assembled full context snapshot.",
      contextSnapshot: {
        patientId: req.patientId,
        toothId: req.toothId,
      },
      result: {
        mockDiagnosis: `Analysis for Tooth ${req.toothId}: Mild caries and surface discoloration detected.`,
        confidence: 0.88,
        recommendedProcedure: "Occlusal composite restoration & fluoride varnish",
        urgency: "Medium",
      },
    };
  },

  sendChatMessage: (userText: string): ChatMessageStub => {
    return {
      id: String(Date.now()),
      sender: "assistant",
      text: "AI stack not connected yet — this conversation will be powered by RAG once the AI stack lands.",
      isStub: true,
      createdAt: new Date().toISOString(),
    };
  },

  generateReportPreview: (
    req: ReportGenerationRequest,
    patientName: string,
  ): ReportPreviewResponse => {
    return {
      isMock: true,
      title: req.title || `${req.templateType.toUpperCase()} - ${patientName}`,
      markdownContent: `
# ${req.title || "Clinical Report Preview"}
> **Status:** Mock Report Preview (TODO: AI Generation connected)  
> **Patient:** ${patientName} | **Date:** ${new Date().toLocaleDateString()}

---

### 1. Executive Summary
Patient presented for routine examination and AI diagnostic assessment. Key findings include localized enamel fissural staining on lower molars.

### 2. Clinical Findings & Dental History
- **Tooth 36:** Previous Class I composite restoration; mild margin discoloration noted.
- **Periodontal Health:** Mild cervical gingival inflammation; overall probing depth < 3mm.
- **Allergies & Risk Factors:** Penicillin allergy noted in medical history.

### 3. AI Evidence & Recommended Plan
1. **Targeted Assessment:** Schedule follow-up digital imaging for Tooth 36.
2. **Prophylaxis:** Apply high-concentration fluoride varnish on occlusal pits.
3. **Patient Advice:** Maintain twice-daily fluoride brushing and interdental flossing.

---
*Generated by Ora AI Clinical Workspace Stub Engine*
      `.trim(),
    };
  },
};
